FROM ubuntu

#install dependencies#LIBRARIES 
RUN apt-get update
RUN apt-get install -y dotnet6 dotnet-runtime-6.0 yt-dlp python3-brotli wget cron dpkg nano 
#Set timezone
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG user=appuser
ARG group=appuser
ARG uid=1000
ARG gid=1000

RUN groupadd -g ${gid} ${group} && useradd -u ${uid} -g ${group} -s /bin/sh -m ${user}
