
FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine

RUN apk update && apk add dpkg yt-dlp py3-brotli bash 
RUN wget  https://github.com/lancer1977/ytdlp-runner/releases/download/alpha/ytdlrunner_0.0.4-4_all.deb
RUN dpkg  --force-all --install ytdlrunner_0.0.4-4_all.deb
RUN chown root /usr/bin/ytdlrunner
RUN chmod 777 /usr/bin/ytdlrunner
RUN addgroup -S appgroup && adduser -S runner -G appgroup
USER runner

ENTRYPOINT ["ytdlrunner"]